from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float, JSON
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class FlightData(Base):
    __tablename__ = 'flight_data'

    ts = Column(JSON)  # OBJECT
    source = Column(String)
    sender = Column(String)
    receiver = Column(String)
    created = Column(JSON)  # OBJECT
    fn_carrier = Column(String)
    fn_number = Column(Integer)
    fn_suffix = Column(String)
    day_of_origin = Column(JSON)  # OBJECT
    local_day_of_origin = Column(JSON)  # OBJECT
    initial_day_of_origin = Column(JSON)  # OBJECT
    local_initial_day_of_origin = Column(JSON)  # OBJECT
    flight_modified = Column(String)
    flight_oper_status = Column(String)
    flight_last_update_userid = Column(String)
    flight_last_update_timestamp = Column(JSON)  # OBJECT
    flight_legs = Column(Integer)
    flight_changed_legs = Column(Integer)
    leg_modified = Column(String)
    leg_no = Column(Integer)
    update_key = Column(Integer)
    state = Column(String)
    old_state = Column(String)
    counter = Column(Integer)
    callsign = Column(String)
    old_callsign = Column(String)
    change_code = Column(String)
    seq_no = Column(Integer)
    old_seq_no = Column(Integer)
    departure_status = Column(String)
    arrival_status = Column(String)
    best_arrival_time = Column(JSON)  # OBJECT
    etops_status = Column(String)
    old_etops_status = Column(String)
    departure_airport = Column(String)
    departure = Column(JSON)  # OBJECT
    dep_apt_utc_difference = Column(String)
    arrival_airport = Column(String)
    arrival = Column(JSON)  # OBJECT
    arr_apt_utc_difference = Column(String)
    service_type = Column(String)
    aircraft_owner = Column(String)
    subtype = Column(String)
    aircraft_configuration = Column(String)
    prev_registraion = Column(String)
    registration = Column(String)
    employer_cabin = Column(String)
    employer_cockpit = Column(String)
    old_departure_airport = Column(String)
    old_departure = Column(JSON)  # OBJECT
    old_dep_apt_utc_difference = Column(String)
    old_arrival_airport = Column(String)
    old_arrival = Column(JSON)  # OBJECT
    old_arr_apt_utc_difference = Column(String)
    old_service_type = Column(String)
    old_aircraft_owner = Column(String)
    old_subtype = Column(String)
    old_aircraft_configuration = Column(String)
    old_registration = Column(String)
    old_employer_cabin = Column(String)
    old_employer_cockpit = Column(String)
    estimated_time_departure_modified = Column(String)
    estimated_time_departure = Column(JSON)  # OBJECT
    estimated_time_takeoff_modified = Column(String)
    estimated_time_takeoff = Column(JSON)  # OBJECT
    estimated_time_touchdown_modified = Column(String)
    estimated_time_touchdown = Column(JSON)  # OBJECT
    estimated_time_arrival_modified = Column(String)
    estimated_time_arrival = Column(JSON)  # OBJECT
    offblock_time_modified = Column(String)
    offblock_time = Column(JSON)  # OBJECT
    airborne_time_modified = Column(String)
    airborne_time = Column(JSON)  # OBJECT
    landing_time_modified = Column(String)
    landing_time = Column(JSON)  # OBJECT
    onblock_time_modified = Column(String)
    onblock_time = Column(JSON)  # OBJECT
    diversion_airport = Column(String)
    old_estimated_time_departure = Column(JSON)  # OBJECT
    old_estimated_time_takeoff = Column(JSON)  # OBJECT
    old_estimated_time_touchdown = Column(JSON)  # OBJECT
    old_estimated_time_arrival = Column(JSON)  # OBJECT
    old_offblock_time = Column(JSON)  # OBJECT
    old_airborne_time = Column(JSON)  # OBJECT
    old_landing_time = Column(JSON)  # OBJECT
    old_onblock_time = Column(JSON)  # OBJECT
    old_diversion_airport = Column(String)
    dep_gate_modified = Column(String)
    dep_gate = Column(String)
    dep_stand_modified = Column(String)
    dep_stand = Column(String)
    arr_gate_modified = Column(String)
    arr_gate = Column(String)
    arr_stand_modified = Column(String)
    arr_stand = Column(String)
    old_dep_gate = Column(String)
    old_dep_stand = Column(String)
    old_arr_gate = Column(String)
    old_arr_stand = Column(String)
    leg_last_update_userid = Column(String)
    leg_last_update_timestamp = Column(JSON)  # OBJECT